runtime: php
env: flex

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2

runtime_config:
  document_root: public   #folder where index.php is

skip_files:
  -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:5SuFgFTBEHaOuE+sFYSBKEU6oa3cvEK6OLA85YGVi8Y=
  STORAGE_DIR: /tmp  
  DB_CONNECTION: mysql  
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: skripsi
  DB_USERNAME: root
  DB_PASSWORD: Xxxtentacion999@
  DB_SOCKET: "/cloudsql/united-helix-270107:asia-southeast2:sistemmonitoring"

beta_settings:
  cloud_sql_instances: "united-helix-270107:asia-southeast2:sistemmonitoring"