runtime: php
env: flex

automatic_scaling:  
  max_num_instances: 1

runtime_config:
  document_root: public   #folder where index.php is

skip_files:
  -.env

env_variables:
  APP_LOG: errorlog
  APP_DEBUG: true
  APP_KEY: base64:5SuFgFTBEHaOuE+sFYSBKEU6oa3cvEK6OLA85YGVi8Y=
  STORAGE_DIR: /tmp