version: '3.5'
services:
  laravel-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: laravel-app
    depends_on:
      - cloud-sql-proxy
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
      DATABASE_URL: mysql://root:@cloud-sql-proxy:3306/skripsi
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      backend:
        aliases:
          - laravel-app
  
  cloud-sql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    # Port: MySQL (3306), PostgreSQL (5433)
    command: /cloud_sql_proxy -instances=rugged-choir-296703:asia-southeast1:skripsi=tcp:0.0.0.0:3306
    volumes:
    # this mounts your application default credential on the container, preventing the
    # 'invalid json file "/config": google: read JWT from JSON credentials: 'type' field is "authorized_user" (expected "service_account")'
    # error if you point to the actual credential file directly
    - ~/.config:/root/.config
    ports:
    - 3306:3306

networks:
  backend:
    name: backend-network 